title: "embed-me"
navicon: "/assets/favicon-32x32.png"
description: >-
  FPGA, Embedded Linux, Reverse Engineering, Hacking,...
baseurl: ""
url: ""

usernames:
  github: embed-me
  twitter: Luki14
  linkedin: lukaslichtl
  
markdown: kramdown
remote_theme: chesterhow/tale

permalink:      /:title
paginate:       5

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lukas Lichtl"
