title: embed-me
description: >-
  FPGA, Embedded Linux, Reverse Engineering, Hacking,...
baseurl: ""
url: ""

github_username: embed-me
twitter_username: Luki14
linkedin_username: lukaslichtl
  
markdown: kramdown
theme: tale

permalink:      /:title
paginate:       5

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lukas Lichtl"
